### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by faccboy** [leonv024/RAASNet#102]
I have a few questions if I may:

1) What's the relation between the RaaSNET v2.0.1 local server and the onion site? How do they communicate?
2) There's a test_socket.py file, should I change the IP address and port used to something specific? Most likely the IP address is my "attack VM", but what about the port, is it hardcoded to be 8989 or I can change to anything else?
3) When I create the payload.py and decryptor.py files, it was not clear where the drecryption key was saved.
4) I could successfully create a network with 2 VMs, "attack VM" and "victim VM", the payload works as it encrypts the files in the VM, but there's no communication with the "attack VM" after I started the server, how can I troubleshoot?

Thanks in advance!

**Comment by leonv024** [comment]
1. What's the relation between the RaaSNET v2.0.1 local server and the onion site? How do they communicate?
**_The server sends the received data to zeznzo.nl/post.py, which sends it through tor to the onion domain. zeznzo.nl is a public endpoint and communication site for the onion site._**

2. There's a test_socket.py file, should I change the IP address and port used to something specific? Most likely the IP address is my "attack VM", but what about the port, is it hardcoded to be 8989 or I can change to anything else?
**_You should change it to the host and port you're hosting the RAASNet server on. If your server is hosted on 10.0.2.11 port 4529, you should change the IP and port in test_socket.py to that settings._**

3. When I create the payload.py and decryptor.py files, it was not clear where the drecryption key was saved.
**_The decryptor is created in the same directory as the payload. The key is sent to the server once you execute the payload. Note that if the payload fails to contact the server, the key is lost and you cannot decrypt your data._**

4. I could successfully create a network with 2 VMs, "attack VM" and "victim VM", the payload works as it encrypts the files in the VM, but there's no communication with the "attack VM" after I started the server, how can I troubleshoot?
**_You should check your VM's network settings. Possibly they were isolated. Try ping the other VM. If that doesn't work, try changing your adapter settings in the VM settings. If all fails, you can set the adapter to Bridged, WHICH IS HIGHLY INSECURE WHEN RUNNING MALWARE._**
