### ISSUE TITLE
It says [Errno 111] Connection refused when i try to run test_socket.py

### ISSUE THREAD

**Issue by tysudo** [leonv024/RAASNet#107]
It says [Errno 111] Connection refused when i try to run test_socket.py

**Comment by leonv024** [comment]
More context, please. What are your server settings and did you change them in test_socket.py?

Is the server running from RAASNet.py? test_socket.py connects to 127.0.0.1 on port 8989 by default. This is also the default setting for the server. If you change nothing in the server settings, it should work.

**Comment by tysudo** [comment]
moved OS' it works now
