### ISSUE TITLE
decryptor error

### ISSUE THREAD

**Issue by Nicolasaandreas** [leonv024/RAASNet#11]
thank you again for the previous problem. It encrypts nicely.

but when I use decryptor, I select the C: \ directory and it does not decrypt passwords.

it is necessary to enter individual folders, for example, decrypting when I make C: \ program Files \ winrar

**Comment by leonv024** [comment]
Hi there,

I reviewed your issue and was able to reproduce.

It had the same problem as the encryptor earlier.
When a permission error occurs it would just break the operation.

I applied a fix.

Could you please try it again?
Don't forget to run the decryptor as administrator if you want to decrypt files in C:\

**Comment by Nicolasaandreas** [comment]
thank you, it works fine

Good luck.
