### ISSUE TITLE
Question: Host & Domain

### ISSUE THREAD

**Issue by SirDeveloperOrg** [leonv024/RAASNet#121]
Hi, first of all I want to thank you for your hard works.
I have a question I'll be appreciated if you could answer it.
How your domain and host is not blocked? Are you using bulletproof host & domain? If yes where can I buy it?
Regards.

**Comment by leonv024** [comment]
I have no fucking clue mate. This sh*t is redundant AF and I don't know why it is still up.

**Comment by SirDeveloperOrg** [comment]
Can you share your discord please?
