### ISSUE TITLE
Data does not appear in Server Window, and how do I get the decryption key.

### ISSUE THREAD

**Issue by volston7** [leonv024/RAASNet#122]
I've able to encrypt in successfullly but I'm facing problems with the server not registering it and "1 Windows PC" and I'm not able to get the decryption key. When I run to open keys.zeznzo.nl to search for the key, a random website  pops up

![image](https://user-images.githubusercontent.com/75581690/179355750-4ea16cd8-bd4e-41ef-b104-bd8e3c6d79cc.png)

![image](https://user-images.githubusercontent.com/75581690/179353932-74c40d83-b3f5-4e4b-a7db-8079a2ff6bc7.png)

**Comment by leonv024** [comment]
This is because the server was not setup properly. It runs locally. If you see no key in the server log, you did something wrong with setting it up. This is why you should test the connection with the server with 'test_socket.py' or use the 'Ghost' encryption option so it only renames the files.

**Comment by volston7** [comment]
I'm using a kali machine to run this and I've a host ip of 127.0.0.1. So I changed the host in the test_socket.py and run it and get a reply "Message Sent". So after running the server, I tried to open the browser and type 127.0.0.1:8989 and it says "Connection Refused". How do u resolve this?

PS: Thanks for the quick reply!

**Comment by leonv024** [comment]
Open the server on said port and 127.0.0.1. Then run test_socket.py. Data should appear in the server window.

Use the ip and port from test_socket.py for your payload. Then you're set.

No browser involved.

**Comment by volston7** [comment]
I'm still facing the same problem
![image](https://user-images.githubusercontent.com/75581690/179472522-48decd71-a69e-434f-ab23-74c6cc681ced.png)

![image](https://user-images.githubusercontent.com/75581690/179472825-6f52ac20-3115-458e-b5e1-4547c46dd0aa.png)

![image](https://user-images.githubusercontent.com/75581690/179472918-e89dddd7-49fc-4540-92b4-1280c3958b6a.png)

But after running the test_socket and getting a successful message, I don't see anything in the server log. 

I have firewall disabled as well

**Comment by volston7** [comment]
I looked into it further and I thought maybe I should run the RAASNet.py with python3.7 but that gives an error even before it runs. "Tkinker not available for this version of python"

**Comment by leonv024** [comment]
@volston7 clone it again and please let me know if this works.

**Comment by leonv024** [comment]
I've removed the geoip requirement and am using ip api, again. This should resolve the issues with the server. I've tested this fix on MacOS (Intel and M1) which worked.

**Comment by leonv024** [comment]
Tested on Kali, working. Awaiting your results. @volston7

**Comment by volston7** [comment]
Hi @leonv024,

I appreciate the fact that you acknowledge it as an bug and fixed it in a short period of time! You've got some great programming skills :)

Yes, I tested it in Kali and it works

However I found a couple of issues:
1. When you set the working directory as $HOME, the encryption doesn't work. I replaced it with /home/volston and it worked
2. A cool feature to have - Is there a way to encrypt all the files in the working directly, cuz currently it only encrypts the code mentioned as the target directory, if nothing is mentioned, the encryption doesn't work
3. This is a stupid one but you can copy the key from the server window with Ctrl+C or Ctrl+Shift_C. I had to manually type it in

If these can be resolved, that would be awesome!

**Comment by volston7** [comment]
@leonv024  let me know we can implement this!

**Comment by leonv024** [comment]
@volston7 

1. $HOME should insert code that finds the user's home directory. I'll look into it.
2. If you set the Target dir to: . (aka dot), then it should encrypt all files in the working directory.
3. It behaves as a terminal, so SHIFT+CTRL+C or select and Right_mouse button should copy the text. But I guess I could make this easier and more obvious.

**Comment by volston7** [comment]
Thanks @leonv024. I really appreciate it!
