### ISSUE TITLE
Server is not working in Kali

### ISSUE THREAD

**Issue by volston7** [leonv024/RAASNet#123]
more info: https://github.com/leonv024/RAASNet/issues/122

**Comment by leonv024** [comment]
Fixed.

![working](https://user-images.githubusercontent.com/33411715/180611122-ea1abcb6-3770-4d81-91ac-c356869b6400.jpeg)

**Comment by leonv024** [comment]
Fixed, see #122 and [https://github.com/leonv024/RAASNet/commit/73eee94e51f5f36b940623fcdc6ca6b2358bcf66](url)

**Comment by leonv024** [comment]
Resolved in last commit.
