### ISSUE TITLE
Pymsgbox isn't building. Any one pls tell me how to build.   When I am run this command Sudo Pip3 install pymsgbox   I have found errors🙄🙄.

### ISSUE THREAD

**Issue by Nirajsingh911** [leonv024/RAASNet#126]
![IMG_20220728_124558](https://user-images.githubusercontent.com/101064463/181447264-d332c1e5-b855-45d3-a0d1-b74312e636a5.jpg)

**Comment by leonv024** [comment]
On Kali it is possible that other packages use some of the requirements, such as mitmproxy. Check the full error. Does it complain about any other tools installed?
