### ISSUE TITLE
URGENT: Keys lost

### ISSUE THREAD

**Issue by MohamedNourTN** [leonv024/RAASNet#14]
Hello sir i tried the RAASNet on my computer so when its starts the decryption key appears and disappears very quickly so please what should I do when i lost my decryption key (host: localhost)

**Comment by leonv024** [comment]
I don't understand why the key would disappear from the server. Remember, you can scroll up and down in the server log.

However, use test_socket.py to test the remote server connection so you are certain the keys can be received.

The best way to store them is to check  the box that says "Save keys on raasnet.zeznzo.nl" when you open up the server.
It'll send the key to your C&C profile on: jezsjxtthkqhlqoc.onion, which you can visit with TOR browser.

The key will remain there until deleted by the user itself.

NOTE:
THERE IS NO WAY TO DECRYPT THE FILES WITHOUT THE KEY.

**Comment by leonv024** [comment]
I do want to add that; if you use the "Copy and Remove" method, it is possible to restore the original file with a advanced file recovery tool.

This method is more likely to bypass write protected files.

It reads the original file, encrypts the content, writes the encrypted content to a new file, adds a new extension, then removes the original file, which (i've tested) can be recovered.
