### ISSUE TITLE
remote server error

### ISSUE THREAD

**Issue by Mrcosta20** [leonv024/RAASNet#15]
good night a question why when I put in remote server the address of open vpn does not work example (huyerqery-87549.pormat.io:87549) I already made in test with the python3 test_socket.py but the only thing that dueve me is TIME OUT no more. my question the program does not work with addresses like no ip or like open vpn. but with direction of the local machine if it works and clarify if I am adding the ports well both inside and outside and the firewal already has the ports added well. some help

**Comment by leonv024** [comment]
Good morning,

Note if you're using a VPN you can only receive keys of victims on a remote network.
You cannot use the server with a VPN if the victim is on the same network. It'll result in a Time out.
