### ISSUE TITLE
What u mean

### ISSUE THREAD

**Issue by Haxxpost** [leonv024/RAASNet#18]
Who's IP do i put for the host?

**Comment by leonv024** [comment]
**Short answer:**
The local IP of the interface you want to use, or you could enter; 0.0.0.0 to bind it to all interfaces.

**Long answer:**
Example:
Your PC has IP: 192.168.0.45
You port forward port 8989 from your router (192.168.0.1) to your PC (192.168.0.45).
You bind the server to 0.0.0.0 on your PC.

Now you can use RAASNet over the WAN (the whole world).
