### ISSUE TITLE
Update credentials

### ISSUE THREAD

**Issue by pieterhouwen** [leonv024/RAASNet#20]
Hi Leon,

You might want to change the credentials on zezno.nl unless of course it's for demonstration purposes :)

I do like your site layout and features on the dashboard.

Take care ;)

**Comment by leonv024** [comment]
Hi Pieter,

Who's credentials?

I don't know what you're talking about but zeznzo.nl is just a demo site.
There's nothing on there that concerns me.

**Comment by leonv024** [comment]
haha, I noticed. I banned the user.

Someone created a account with username admin and password admin.
It's not my user and certainly not an Admin.
