### ISSUE TITLE
no display name and no $DISPLAY 

### ISSUE THREAD

**Issue by meetgyn** [leonv024/RAASNet#27]
root@ubuntu:/opt/Projetos/RAASNet# python3 RAASNet.py 
Traceback (most recent call last):
  File "RAASNet.py", line 1580, in <module>
    logon = Login()
  File "RAASNet.py", line 129, in __init__
    Tk.__init__(self)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
root@ubuntu:/opt/Projetos/RAASNet# 
I tried on windows, now I'm trying on ubuntu and nothing. Can you help?

**Comment by ch-rigu** [comment]
are you over ssh ? if so, run it direct in the vm or host.
I had this error over ssh.
cheers.

**Comment by meetgyn** [comment]
I ran it directly from the VM.
I tried with Ubuntu. Then I tried with Windows 10. However, in no system I was able to make it work.

**Comment by MIDER3** [comment]
Same problem http://prntscr.com/va65ly

**Comment by b4sh1t1** [comment]
same problem with different distro; i suggest use a docker image for quick and flexible installation.

**Comment by leonv024** [comment]
Because it has a GUI, so it doesn't work on a terminal only server.
Install a desktop environment and connect via VNC or NoMachine to your host.
