### ISSUE TITLE
server not running!

### ISSUE THREAD

**Issue by ricko2991** [leonv024/RAASNet#29]
Hi, can you help me, I managed to run the payload.exe and it works, then I try to run server and no incoming connection. But i want to test it to ensure the server is running or not:
python3 test_socket.py

And then give me error message:
"timed out"

**Comment by leonv024** [comment]
test_socket.py sends a message to 127.0.0.1 on port 8989. If the server is not running there, it won't receive.

1. Start the server on ip 127.0.0.1 and port 8989
2. Run test_socket.py
3. It should receive.

**Comment by ricko2991** [comment]
I run it as you say. But the problem may be about the operating system I use. i use windows to run the server. But I try to keep running "test_socket.py" and it always fails. Are there any settings I need to fix in windows?

**Comment by leonv024** [comment]
No, it should work on Windows without changing any settings or firewall issues.

**Comment by ricko2991** [comment]
Why can't i do it?

**Comment by ricko2991** [comment]
i have also tried it on linux (times) but still can't do test_socket.py
