### ISSUE TITLE
unable to register 

### ISSUE THREAD

**Issue by HugoLGF** [leonv024/RAASNet#30]
when i try to register i have this error ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

**Comment by leonv024** [comment]
Try visit https://zeznzo.nl/reg.py with browser

You should see a Unable to process error.

OR

You'll see a Firewall notice that you have been graylisted. You'll need to verify you're human and that should lift the IP ban.

OR

You cannot register from China. China was banned from the server for throwing tons of bots at it.

Hope this helps.

**Comment by leonv024** [comment]
If all else fails, try creating an account on the onion panel. They work on the client too.

**Comment by HugoLGF** [comment]
where is the onion panel url

**Comment by leonv024** [comment]
At the top of the ReadMe.

http://jezsjxtthkqhlqoc.onion/login/register.py

**Comment by HugoLGF** [comment]
so i've created my acc on the onion panel but when i try to log in with the app it doesnt work and i have this error   
File "C:\Users\toto\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

**Comment by leonv024** [comment]
Strange. Look up the issue. Seems like a permission error from the local system and has nothing to do with the remote connection.

Some people state that running it as root/administrator resolve the issue but that not a fix in imo.

What version of requests are you running?
What does `pip3 show requests` say?
