### ISSUE TITLE
Traceback (most recent call last):   File "RAASNet.py", line 1531, in <module>

### ISSUE THREAD

**Issue by MIDER3** [leonv024/RAASNet#31]
HELP
http://prntscr.com/va65ly
Traceback (most recent call last):
  File "RAASNet.py", line 1531, in <module>
    logon = Login()
  File "RAASNet.py", line 148, in __init__
    Tk.__init__(self)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by leonv024** [comment]
Looks like you use Windows Subsystem for Linux.

WSL is just a terminal and cannot open apps with a GUI.
There is a work around to open this on a terminal by using a vnc server.

Here's a demo on Android 10 on how to open RAASNet on a terminal device using VNC:
https://www.youtube.com/watch?v=Lar8CDbkUqo&t=2s

Note the following:
Running RAASNet:
vncserver -localhost
export DISPLAY=":1"
python RAASNet.py

Connect VNC to localhost:5901

But.. tbh, just use a GUI machine, like a VM.
