### ISSUE TITLE
files not encrypting

### ISSUE THREAD

**Issue by phoxxy420** [leonv024/RAASNet#32]
When I send the compiled application through desktop sharing software to my target and open it, the files all appear to be encrypted with .DEMON and the payload seems to execute properly. However, when I rename the "encrypted" file and erase the .DEMON extension, the file is able to be opened normally with no decryptor necessary. Am I doing something wrong or is this an issue? Also I have no infected computers show up in my demonware server window. Thank you for the framework and I plan on donating as soon as I can get this to run successfully.

**Comment by leonv024** [comment]
Hi there,

Sorry for the delay. Been on a holiday last week.

Anyway, this sounds like the Ghost type of ransomware.
I've build multiple types of encryption in the RAASNet generator.

If you select Ghost, the payload renames the files with a new extension.

Please note:
Wiper : Destory the files (fastest)
Ghost : Rename the files (fastest)
PyAES : Encrypt the files (slowest)
PyCrypto : Encrypt the files (fast)

The server is binds to your network.
If you want to use this remote, you'll need to setup port forwarding on your router, and set the remote IP in the payload the IP or domain you're hosting demonware on.

**Comment by phoxxy420** [comment]
Thank you for answering at all! I am a big fan of your work here. I love the interface and all of it, so cool.

This helps a lot me you are correct, I was using the Ghost type ransom. I will play around with the network/server tonight and hopefully get it to work. 

I have lots of targets who want to be hacked through a sort of hacking dominatrix fetish and this helps me a lot I have very basic programming experience. I will certainly be sharing the bounties of my first victim as thanks
