### ISSUE TITLE
docker image request.

### ISSUE THREAD

**Issue by b4sh1t1** [leonv024/RAASNet#34]
Hello;

As per there is some old packages requested for installation i get the software working file from fresh VPS with different distro as below;

sudo apt update
sudo apt upgrade
sudo apt install wget python3-pip nano mlocate git -y
sudo apt install python3-tk python3-pil python3-pil.imagetk
git clone https://github.com/leonv024/RAASNet.git
pip3 install -r requirements.txt
python3 RAASNet.py

after running this i receive error;
no display name and no $DISPLAY

my suggestion to build a docker image so we can run it quickly and easy.

**Comment by leonv024** [comment]
That's because you're trying to run this app on a terminal only server, wich as no display. It has a GUI so it only works on a desktop environment, like Kali, Windows or MacOS.

**Comment by b4sh1t1** [comment]
Thanks for clear the question.
