### ISSUE TITLE
Code execution

### ISSUE THREAD

**Issue by YasirAsim** [leonv024/RAASNet#35]
Hi, I'm in beginning stage, so don't have an advanced knowledge of CLI. Can anybody please tell me how can I run this code into window 10??? Same as the attached graphically UI images of RAATNas into description. 
Thank you in advance.

**Comment by leonv024** [comment]
You don't need advanced CLI knowledge.
All you need to know it how to install and run a python script.

On Windows:
+ Install python 3.7 or later
+ During the installation, check the box that says: Add to PATH
+ Unzip RAASNet-main.zip and copy, paste it to your desktop
+ Open cmd
+ Navigate to the download directory/RAASNet directory (example: cd Desktop/RAASNet-main/)
+ Use command: pip3 install -r requirements.txt
+ Use command: py RAASNet.py

If this doesn't work out for you, search "raasnet" on youtube.

**Comment by YasirAsim** [comment]
After following your mentioned steps, I'm getting this error. 

C:\Users\Administrator\Desktop\RAASNet-master>py RAASNet.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\RAASNet-master\RAASNet.py", line 58, in <module>
    import PIL.Image, PIL.ImageTk
ModuleNotFoundError: No module named 'PIL'

**Comment by YasirAsim** [comment]
Okay, Finally I'm able to run RAASNet.py, but unfortunately after compiling payload, my window defender automatically removed this file. 
Is there anyway to FUD this payload from Window 10 defender?

**Comment by YasirAsim** [comment]
Also When I run the payload after disabling window defender, Nothing is happen, No any file format changed. It's not working for me
