### ISSUE TITLE
Kali Linux test_socket.py Errr 111

### ISSUE THREAD

**Issue by anwarcui** [leonv024/RAASNet#38]
kali@kali:~/Desktop/RAASNet-master$ python3 test_socket.py
[Errno 111] Connection refused
kali@kali:~/Desktop/RAASNet-master$ 

In window working it but in kali linux not working 
Why this is happening here error??

**Comment by leonv024** [comment]
Connection refused happens when the port has no service running behind it. Likely, the server wasnt running when you executed test_socket.py.
