### ISSUE TITLE
c & c login disable

### ISSUE THREAD

**Issue by nocomp** [leonv024/RAASNet#39]
hi,
i wanted to give a shot, but i ve noticed we can t login on c & c pannel (onion url), any idea why?
best regards

**Comment by leonv024** [comment]
No... Your RAASNet account is also valid for the onion C&C.

**Comment by nocomp** [comment]
thxxx @leonv024  bt can t clic on the button, tried on linux or windows

**Comment by leonv024** [comment]
Oh, hahaha, whoops. I didn't notice because I always hit Enter. Refresh the page. It should be fixed now.

**Comment by nocomp** [comment]
like a charm :)))
