### ISSUE TITLE
Windows Python module issue

### ISSUE THREAD

**Issue by nocomp** [leonv024/RAASNet#40]
hellooooo,
i am trying to setup a box on winblows for compile purpose, but, event pip3 install went smooth, running the python file give me an error:

PS C:\Users\nocomp\tools\ransomware\RAASNet> pip3 install PIL
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'c:\users\nocomp\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.
PS C:\Users\nocomp\tools\ransomware\RAASNet> pip3 install -r .\requirements.txt
Requirement already satisfied: pymsgbox in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 1)) (1.0.9)
Requirement already satisfied: pyaes in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 2)) (1.6.1)
Requirement already satisfied: pycryptodome in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 3)) (3.9.9)
Requirement already satisfied: pyinstaller in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 4)) (4.1)
Requirement already satisfied: requests in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 5)) (2.25.0)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller->-r .\requirements.txt (line 4)) (2020.10)
Requirement already satisfied: pywin32-ctypes>=0.2.0; sys_platform == "win32" in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller->-r .\requirements.txt (line 4)) (0.2.0)
Requirement already satisfied: setuptools in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller->-r .\requirements.txt (line 4)) (49.2.1)
Requirement already satisfied: pefile>=2017.8.1; sys_platform == "win32" in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller->-r .\requirements.txt (line 4)) (2019.4.18)
Requirement already satisfied: altgraph in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller->-r .\requirements.txt (line 4)) (0.17)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from requests->-r .\requirements.txt (line 5)) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from requests->-r .\requirements.txt (line 5)) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from requests->-r .\requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from requests->-r .\requirements.txt (line 5)) (2020.11.8)
Requirement already satisfied: future in c:\users\nocomp\appdata\local\programs\python\python39\lib\site-packages (from pefile>=2017.8.1; sys_platform == "win32"->pyinstaller->-r .\requirements.txt (line 4)) (0.18.2)
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'c:\users\nocomp\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.
PS C:\Users\nocomp\tools\ransomware\RAASNet>

PS C:\Users\nocomp\tools\ransomware\RAASNet> python RAASNet.py
Traceback (most recent call last):
  File "C:\Users\nocomp\tools\ransomware\RAASNet\RAASNet.py", line 58, in <module>
    import PIL.Image, PIL.ImageTk
ModuleNotFoundError: No module named 'PIL'
PS C:\Users\nocomp\tools\ransomware\RAASNet>

in order to get it working i had to pip install image, maybe it should be added to the requirement list?
hope it helps!

**Comment by leonv024** [comment]
Thank for the mention. However, I'll have to test if adding this requirement works with RAASNet on Windows or Mac.

**Comment by nocomp** [comment]
No prob,
I thought it would be good to share this with you

**Comment by leonv024** [comment]
Verified. Seems to be an python 3.9.1 issue. pip3 install pillow fixes it. Also numpy is broken on Windows, which means you can't compile the payload. Added a workaround for that aswell.
