### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Flamingo6** [leonv024/RAASNet#42]
![image](https://user-images.githubusercontent.com/75337682/102294324-11c73e00-3f17-11eb-952a-67abfce9a9c6.png)
Before this I did download requirements, I can't run the script

**Comment by Flamingo6** [comment]
Python wasn't installed correctly, when I generate my payload and decrypter it doesn't actually go in my files and there is nothing on the cmd?
![image](https://user-images.githubusercontent.com/75337682/102300196-7936bb00-3f22-11eb-9d80-1fc9536b54ee.png)

**Comment by leonv024** [comment]
Ok, so this is new. Since there are no errors in the console they must have been written somewhere. Note that it writes the files to the directory RAASNet was executed from, which in your case would be C:\Users\flame\RAASNet\payload.py.

**Comment by Flamingo6** [comment]
Thanks, didn't realize that the directory was off, now I have another problem I'm trying to compile the payload and it saids it' in the dist folder but it wasn't created? Something is wrong with my python, I tried uninstalling and reinstalling it and here's the error. 
![image](https://user-images.githubusercontent.com/75337682/102443923-e36c6000-3ff5-11eb-8b52-0812141a665d.png)

**Comment by Flamingo6** [comment]
![Uploading image.png…]()
