### ISSUE TITLE
error register

### ISSUE THREAD

**Issue by cymilad** [leonv024/RAASNet#44]
I want to register but with this problem 

![Capture](https://user-images.githubusercontent.com/22496001/102714051-8ddbd000-42e1-11eb-9c6f-06906e6264b9.PNG)

**Comment by leonv024** [comment]
You're likely missing some SSL modules. Don't know why because they should be OK after installing requests.

Try this:
pip3 install ndg-httpsclient
pip3 install pyopenssl
pip3 install pyasn1

**Comment by TerryJLU** [comment]
He used Proxy

**Comment by leonv024** [comment]
> He used Proxy

Possibly...

**Comment by cymilad** [comment]
How do I do it?

**Comment by bobwatcherx** [comment]
i am register and show alert this bellow

" FAILED TO REGISTER 404 "
 
can you solved my error
