### ISSUE TITLE
Whole device not encrypting using option overwrite and rename method .

### ISSUE THREAD

**Issue by SexureCode** [leonv024/RAASNet#56]
I tried to encrypt all directories in c:/ but unfortunately its not working in overwrite and rename method .But its working when i used the copy and remove method.And also when i use copy and remove method.The files are copied and encrypted but the files are not removing .You got any solution ? Thank you so much. Hope you reply me as soon as possible.

**Comment by leonv024** [comment]
First things first: Did the payload run as admin?

Note that not even an admin and delete or rewrite some files in System32 and other sensitive directories on C:/.

Can you please run the payload in console mode with debug enabled? (use the terminal to execute the payload: `py payload.py`)
It should print out errors and tell why it cannot encrypt or delete the files.

please post the debug log. (a sample will do, likely its the same error on every file.)
