### ISSUE TITLE
il programma non esegue la crittografia 

### ISSUE THREAD

**Issue by rudymentalewatson** [leonv024/RAASNet#58]
buongiorno 
dopo vari tentativi sono riuscito a fare funzionare il programma RAASNet.py 
in particolare ho avuto molti problemi con le librerie
comunque dopo aver fatto la procedura ho compilato un payload e non ho cambiato l'estensione ; l'ho poi copiato su un mio computer che uso come "palestra" e ho aperto il server, 
Appare il messaggio ma i file non vengono crittografati ; credo sia dovuto al server che infatti non parte....non si collega 
il computer dove ho compilato è un windows 10 e ho usato git bash come l'esempio del video 
il computer vittima ( sempre mio) è un windows 8.1 
chi può aiutarmi?
grazie

**Comment by leonv024** [comment]
Enable debug mode, start the payload from the console and post the debug log here so we can track down this issue, thx.

**Comment by rudymentalewatson** [comment]
ok ci provo .....devo trovare il file log.,,

grazie

**Comment by rudymentalewatson** [comment]
if you want I can send the two files I created; the two payloads ...
in the meantime I look for the log file ... I don't know in which folder it is located.

thank's

**Comment by rudymentalewatson** [comment]
setting debug mode no longer compiles the file.
here's what he writes:

$ py RAASNet.py
Exception in Tkinter callback
Traceback (most recent call last):
File "C: \ Users \ Rodolfo \ AppData \ Local \ Programs \ Python \ Python39 \ lib \ tkinter \ __ init__.py", line 1884, in __call__
return self.func (* args)
File "C: \ Users \ Rodolfo \ Desktop \ RAASNet-master \ RAASNet.py", line 945, in compile_payload
payload = open (self.options ['payload_path']. get ()). read ()
OSError: [Errno 22] Invalid argument: './payload.py'

**Comment by rudymentalewatson** [comment]
no this morning is no longer going in any way; gives the same error; also set as in the video of him:
Exception in Tkinter callback
Traceback (most recent call last):
File "C: \ Users \ Rodolfo \ AppData \ Local \ Programs \ Python \ Python39 \ lib \ tkinter \ __ init__.py", line 1884, in __call__
return self.func (* args)
File "C: \ Users \ Rodolfo \ Desktop \ RAASNet-master \ RAASNet.py", line 945, in compile_payload
payload = open (self.options ['payload_path']. get ()). read ()
OSError: [Errno 22] Invalid argument: './payload.py'

**Comment by rudymentalewatson** [comment]
also when I try to compile it the payload.py file disappears from the directory
yesterday did not happen,
it happened today after i set it in debug.

**Comment by rudymentalewatson** [comment]
today's problem is solved; in practice, the file was deleted by windows defender while the compilation was taking place
but I thought it was not found by antivirus.
now i try to send it to the victim computer
update later.

**Comment by rudymentalewatson** [comment]
last update: I compiled the file with a word icon like in the video; then I put it in a USB stick because by mail it was impossible to send it to the victim computer (all providers recognize it as a virus and block the sending)
inserted the key in the victim computer I ran the file; before running I started the server.
I didn't get any results just like yesterday and it's probably because the connection with the server doesn't open; now I try again with the debug function and I send you the log file.
however, even in the old computer the avg antivirus not updated immediately recognizes it and to try I have to disable it.
where do i find the log file? thank you

**Comment by rudymentalewatson** [comment]
last update: I compiled the file with a word icon like in the video; then I put it in a USB stick because by mail it was impossible to send it to the victim computer (all providers recognize it as a virus and block the sending)
inserted the key in the victim computer I ran the file; before running I started the server.
I didn't get any results just like yesterday and it's probably because the connection with the server doesn't open; now I try again with the debug function and I send you the log file.
however, even in the old computer the avg antivirus not updated immediately recognizes it and to try I have to disable it.
where do i find the log file? thank you

**Comment by rudymentalewatson** [comment]
> Enable debug mode, start the payload from the console and post the debug log here so we can track down this issue, thx.

sorry where can i find the debug log??

**Comment by rudymentalewatson** [comment]
> > Enable debug mode, start the payload from the console and post the debug log here so we can track down this issue, thx.
> 
> sorry where can i find the debug log??

i find this 

<?xml version="1.0" encoding="utf-8"?>
<CodeMeterActDiag>
  <Info datetime="21Feb17/09:59:35" computername="monika" ver="7.10.4196"/>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="136">5aa362525dcd3ce0c71862dec2fcb5bdbd022fd7a98bb93a82c8cfc6ef255f2bfc769546f21715e5b8c5612e4165efc30331942ea4844707ad4060b5a4bad06ce51e764758f8d5bbc32fd529961e1316afb27ee1ac99dc08e71ada5405d3031f62f5676b2fdba0609bfe3b847750874adb9e8a3d6d5c8b99c4356acdbe9fbcf036abdbeb1d47b789f04141460a51c23e</Data>
  <Data size="92">200d649aa3dd6a2a06dfbcc9bd30e7b8bade27f7ffa69e9e7fd20b4c50ad31476ae1bb1bdce802b345010c72bb5dbe712f392963c2cf2f6d64d91ff7add0a7653100990b595889a2851cabef9be119c6e42e9693831df1a2e1c41de065bff93e</Data>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="80">7d4c6829af46ad0ce8f3e69afa244f9cc270ac3c5a3d6b028b05bc4aaea958402a322245c553fdda33fdc56c1050ce92467dd4a91166c462445d7d9ce217344fe7b18f6e387f944b6ae9ac3b6c0a8316</Data>
  <Data size="80">7d4c6829af46ad0ce8f3e69afa244f9cc270ac3c5a3d6b028b05bc4aaea958402a322245c553fdda33fdc56c1050ce92467dd4a91166c462445d7d9ce217344fe7b18f6e387f944b6ae9ac3b6c0a8316</Data>
  <Data size="48">4ed2b638f711274c8ace60a3a3d06a4707d23ca7d9abd8024c56de66a28c7cb3e7614c697262ea78a4d297fdc30c51e4</Data>
  <Data size="64">0da91ad0de32afa97fc96538ba4638206204b7c70bd6f81f2e80d8d1e7bb51f22fdf96678e4f23939f8993883bb6f576c1ef055a4e7e3b0a94adb18aaf1d2f33</Data>
  <Data size="32">821c0599158f7c2617d79e20ab319435be367f244f3cc3f0e993665a78b43d25</Data>
  <Data size="32">5d4013c3320367a6d47f9fe2bdeeb5477309e5acf3b194176dbb2ea1d5fa924e</Data>
  <Data size="80">72fe0aa2f3ae0e8c65cf33f7b89a8bd3e756597dff861eff67768c4704fea4fbae997486584e95422db6b738a059cb79096c99580337f41ab0a756488c1c0fdc5a56cc512b5ce9161a42f1ca405974c6</Data>
  <Data size="176">43acc5a51efc4202ec9e685b4365c5204e54c6ea008a6f09043d7e51b8db525aaf7a99dd1df85efb74b66ed72da78a2c3cb3f997ebdd22fcd6026a7f8c6e052d55e60ce1e02256d5178e9577b95848baebb56d4e3e6888d322d989b7ca7041c6876cfd2488b6ae44f0b9565885584ef79db6dcfa2737348520d926b60e7b6acf87594e6dfe8c9f2751cfcc85ed59f69685f969c8a41c191d78014190f1582b9bc86863e020727cd59b9b0893a192df9c</Data>
  <Data size="32">6fb8647b132c8dba485044a995033412a15d60bc285fb1c6535a449ae924ed10</Data>
  <Data size="32">c859f22b59ee2de1ad6b36ca2388cf60ba45597fca248826892a469aefe5b6f0</Data>
  <Data size="48">f27a11cae003aa796b050d4247e9b597c39bcb850dc0331e25181df854adfb557cde4622fcfa6e3c553db03a2df5b280</Data>
  <Data size="16">942e9ee367f7e2611dc5fd6aa2e1c7fa</Data>
  <Data size="16">9449853cb2d781a3d6064321b0713664</Data>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16cabffd00321386cfb9338627cf2c8e70545c33298403b5ff080bff9353da1f82f</Data>
  <Data size="64">6d65be5e96e2c8afe48749dd4c6d00944564b4e4a28728fbb38882a7034ac827e76ff29209f5ea43c98ca27fd52f6c4375e9730d430305736b3278960643581a</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8ba29cf4a3f3ea7117fd946328df135b78ded0c3af66da43e6797be8bda469fe2e</Data>
  <Data size="48">38973a0ce8ae2d5bcf90805d6c1a8a3f52ab16f5b508d3968b49627b1a89bc16fb6b1ad4699e68c94d78e0787061ee36</Data>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16cabffd00321386cfb9338627cf2c8e7054ab85b15b75ee836d126d529a798289d</Data>
  <Data size="64">6d65be5e96e2c8afe48749dd4c6d00944564b4e4a28728fbb38882a7034ac827e76ff29209f5ea43c98ca27fd52f6c43642bbafc49a57cdd95446ff134f0c4c6</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8b4ef5db7e54e3e263ccd8c80552ab78cbcf79974481ab897507add0fad42c8e35</Data>
  <Data size="48">38973a0ce8ae2d5bcf90805d6c1a8a3f941675e8329c8e2f0fc554bebfb6239156e7ddf0942fd50ed4a04e2bfef27ab3</Data>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16c86960500bcef7f1887499c26c5d569fd9873724c979f493d2639ede44eaf1fce</Data>
  <Data size="64">6d65be5e96e2c8afe48749dd4c6d00944564b4e4a28728fbb38882a7034ac8278cc17d008561ef8c088219cc908050ff38d3531ddf69cfb86383f9e33f069184</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8b29212a1f3fb9a5601b26e3a5aeb8740f4eca7d90e384fd33c8e179db494cc339</Data>
  <Data size="48">38973a0ce8ae2d5bcf90805d6c1a8a3f64d0f8aa84ae943648914f48ee717eba2ef4643fa8c10c5ef2941630dac07a2a</Data>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16c2657ea1e26b0b8e0762ccfc2bb8c7d7c611c06c0454e241092766351a32c8939</Data>
  <Data size="64">6d65be5e96e2c8afe48749dd4c6d00944564b4e4a28728fbb38882a7034ac8274b3e2e053bcea90be916ffa79f0555be65b852de62df9f53dd7c9e1e9e3218e4</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8b8dfb11f9032ae0b6693419a1d2172e93a9f8f76e33c01fca5a03358f344c4fab</Data>
  <Data size="48">38973a0ce8ae2d5bcf90805d6c1a8a3fa2ca38d91c78ee7affc5d6590eb605429989f20cbd9009ab66535640dd191b8e</Data>
  <Data size="64">4f605d1f09c0605a8a7ba69fd457681ced0fcf1d75a8f2c32b00dff73fe02395767a9cfce66672edb89b58e85adbda08a11f235d21ed0791e22d6598f103e716</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8b72acf50b05133e3dc16973fbd92a9e41340ad1fc610070c7d2832f78a54bc3fc</Data>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16cc7f0f89eb7541435b8751fe80b43044ebfc09918442136f7c835311d4db18f56</Data>
  <Data size="64">4f605d1f09c0605a8a7ba69fd457681ced0fcf1d75a8f2c32b00dff73fe0239526ab54a39e0cf7c9032d496aa720277938b04b89fe6ed0c89e13faf8b9ca95ac</Data>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="32">1d207f4be2288d830b9cee0073e06b1cd21c4840f352f8fcd946c2f8d5bd9f77</Data>
  <Data size="32">1d207f4be2288d830b9cee0073e06b1c351e1e880fc87a30d758bb8e135494af</Data>
  <Data size="48">1d207f4be2288d830b9cee0073e06b1c2ec63d68ca07e9ad0144e7140b40739d9ebd3c200ed5e8e18237260e55ba7c2b</Data>
  <Data size="32">1d207f4be2288d830b9cee0073e06b1c82eeafd9acbce6d7704c9973efe9b76c</Data>
  <Data size="112">1d207f4be2288d830b9cee0073e06b1c78a13b1d00c0c2aa82821c47c9cf5f23e6df3b212b6e01df96e9cf93e6c86b5f1480978f32fbcb605d7e3eadd4ad3a6afad74c42c17c5a5dd87232caa1742c030a7dc7f866cb99039bf52b8edc81186bc0eb7fb1806955caa6cb58a55bf74af5</Data>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="896">c2d2be4e86f277107f4946615448592f02f11b2fa2c482713db2aedaaa799f2d10bfc7182193e9620b7b8a45715f794d0cbca6f54f429381e28f9e102a0da42fd42fcf80caba529fa5a954465329e305cbe712c45065261f8531ae99727b903aa11e1338ec4fddd2b2d52e7d83091c64f961600ee10a0abc0cd8e69157eaeb3990ad29352d266d2c8850dd22ed8a538d4a6d78067d674dd20a046b10d294c4601e895255d59fe54f5608fd3b56f9a5854b4530bb8cbaae9f0f32e5f42eb4af67bf7fceabcf4624a1388de9ed6a1b9c144107491045ffc319bbe0bf77a12efb5322515c155188803b1c4670a62c9ad617fe348c5f4d600dd0421be943dc6191944de924e3cfe5811fe14ebbc8c07a48baea83ac343a73be627b4baf0581aedd98d4cd32c3fa4a7c603c9453e8592b1a1038a3ca8d7b3d2a3506902c1b6ba938fc43ab84daf9f98088b9324348adb4c41ba7f6717394c3a13c0176075530f2ea55681e2fda94c27b61648367382ab23d4cdbb3c233b61df7b1811860921868db92eef709a5a90421872fcf71331336702c06cd0a77c1aae0f4cf40b115078e27eec9bf12012426c179bcfbe93227ccc63f01a250152f0ae8e79e0daefd359772843e98a066fa917899fa799384318480667a6e7016e1460b73be65c996a58d18828877067799ba26cfa37a738c8a9ea564e77d81e52a9d974638c81ae587079e64f962479971ef453505f8098877b119d154d54b844b905ccaf98a36b0f85d689c55a411fe2f30d5badba08ef75304ed115e559c1b172e32f0ec24abce2ea82736a1fe1140f96bb82b90dce7363834b02422909e3c0d75b48f9ad5f7b1e87a986be447901cc629f5d2becb938281d85035598028cc0d6e5d083d43612ba942a7cf0a4efc566d8b65637e1e05d7c4c58ba0a6012448753c50bea4a77ec67178036c2514116da20d54aa105427751b3b8e517bcf86b230f6fcf307fbf29fd42e19c2a777613186108d00a1c07b4660eb4c0bac68b195fed8763b7f772e0b9ac2ec3b5aa2b6890b0ac35403fb438ab28921ea4b2691b55fe39cce7609c534736a296f4b3e128975047fccaf67b3ac219b2c227651f8a0e7b64acad86f3c38d72909f3708a90fc36843a4667759a50ff1de1b387ce55d014491bcf4d6aac413450be9d65a2b89733a9fddc867af437c1f3a9d03f5b5fdac29f01cfe9d219cfc85a953b310778fdbccbaf2634e056d301cf8c005fefccaed2e87e4b63e067e3b050756d</Data>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="136">5aa362525dcd3ce0c71862dec2fcb5bdbd022fd7a98bb93a82c8cfc6ef255f2bfc769546f21715e5b8c5612e4165efc30331942ea4844707ad4060b5a4bad06ce51e764758f8d5bbc32fd529961e1316afb27ee1ac99dc08e71ada5405d3031f62f5676b2fdba0609bfe3b847750874adb9e8a3d6d5c8b99c4356acdbe9fbcf036abdbeb1d47b789f04141460a51c23e</Data>
  <Data size="92">200d649aa3dd6a2a06dfbcc9bd30e7b8bade27f7ffa69e9e7fd20b4c50ad31476ae1bb1bdce802b345010c72bb5dbe712f392963c2cf2f6d64d91ff7add0a7653100990b595889a2851cabef9be119c6e42e9693831df1a2e1c41de065bff93e</Data>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="80">7d4c6829af46ad0ce8f3e69afa244f9cc270ac3c5a3d6b028b05bc4aaea958402a322245c553fdda33fdc56c1050ce92467dd4a91166c462445d7d9ce217344fe7b18f6e387f944b6ae9ac3b6c0a8316</Data>
  <Data size="80">7d4c6829af46ad0ce8f3e69afa244f9cc270ac3c5a3d6b028b05bc4aaea958402a322245c553fdda33fdc56c1050ce92467dd4a91166c462445d7d9ce217344fe7b18f6e387f944b6ae9ac3b6c0a8316</Data>
  <Data size="48">4ed2b638f711274c8ace60a3a3d06a4707d23ca7d9abd8024c56de66a28c7cb3e7614c697262ea78a4d297fdc30c51e4</Data>
  <Data size="64">0da91ad0de32afa97fc96538ba4638206204b7c70bd6f81f2e80d8d1e7bb51f22fdf96678e4f23939f8993883bb6f576c1ef055a4e7e3b0a94adb18aaf1d2f33</Data>
  <Data size="32">821c0599158f7c2617d79e20ab319435be367f244f3cc3f0e993665a78b43d25</Data>
  <Data size="32">5d4013c3320367a6d47f9fe2bdeeb5477309e5acf3b194176dbb2ea1d5fa924e</Data>
  <Data size="80">72fe0aa2f3ae0e8c65cf33f7b89a8bd3e756597dff861eff67768c4704fea4fbae997486584e95422db6b738a059cb79096c99580337f41ab0a756488c1c0fdc5a56cc512b5ce9161a42f1ca405974c6</Data>
  <Data size="176">43acc5a51efc4202ec9e685b4365c5204e54c6ea008a6f09043d7e51b8db525aaf7a99dd1df85efb74b66ed72da78a2c3cb3f997ebdd22fcd6026a7f8c6e052d55e60ce1e02256d5178e9577b95848baebb56d4e3e6888d322d989b7ca7041c6876cfd2488b6ae44f0b9565885584ef79db6dcfa2737348520d926b60e7b6acf87594e6dfe8c9f2751cfcc85ed59f69685f969c8a41c191d78014190f1582b9bc86863e020727cd59b9b0893a192df9c</Data>
  <Data size="32">6fb8647b132c8dba485044a995033412a15d60bc285fb1c6535a449ae924ed10</Data>
  <Data size="32">c859f22b59ee2de1ad6b36ca2388cf60ba45597fca248826892a469aefe5b6f0</Data>
  <Data size="48">f27a11cae003aa796b050d4247e9b597c39bcb850dc0331e25181df854adfb557cde4622fcfa6e3c553db03a2df5b280</Data>
  <Data size="16">942e9ee367f7e2611dc5fd6aa2e1c7fa</Data>
  <Data size="16">9449853cb2d781a3d6064321b0713664</Data>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16cabffd00321386cfb9338627cf2c8e70545c33298403b5ff080bff9353da1f82f</Data>
  <Data size="64">6d65be5e96e2c8afe48749dd4c6d00944564b4e4a28728fbb38882a7034ac827e76ff29209f5ea43c98ca27fd52f6c4375e9730d430305736b3278960643581a</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8ba29cf4a3f3ea7117fd946328df135b78ded0c3af66da43e6797be8bda469fe2e</Data>
  <Data size="48">38973a0ce8ae2d5bcf90805d6c1a8a3f52ab16f5b508d3968b49627b1a89bc16fb6b1ad4699e68c94d78e0787061ee36</Data>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16cabffd00321386cfb9338627cf2c8e7054ab85b15b75ee836d126d529a798289d</Data>
  <Data size="64">6d65be5e96e2c8afe48749dd4c6d00944564b4e4a28728fbb38882a7034ac827e76ff29209f5ea43c98ca27fd52f6c43642bbafc49a57cdd95446ff134f0c4c6</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8b4ef5db7e54e3e263ccd8c80552ab78cbcf79974481ab897507add0fad42c8e35</Data>
  <Data size="48">38973a0ce8ae2d5bcf90805d6c1a8a3f941675e8329c8e2f0fc554bebfb6239156e7ddf0942fd50ed4a04e2bfef27ab3</Data>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16c86960500bcef7f1887499c26c5d569fd9873724c979f493d2639ede44eaf1fce</Data>
  <Data size="64">6d65be5e96e2c8afe48749dd4c6d00944564b4e4a28728fbb38882a7034ac8278cc17d008561ef8c088219cc908050ff38d3531ddf69cfb86383f9e33f069184</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8b29212a1f3fb9a5601b26e3a5aeb8740f4eca7d90e384fd33c8e179db494cc339</Data>
  <Data size="48">38973a0ce8ae2d5bcf90805d6c1a8a3f64d0f8aa84ae943648914f48ee717eba2ef4643fa8c10c5ef2941630dac07a2a</Data>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16c2657ea1e26b0b8e0762ccfc2bb8c7d7c611c06c0454e241092766351a32c8939</Data>
  <Data size="64">6d65be5e96e2c8afe48749dd4c6d00944564b4e4a28728fbb38882a7034ac8274b3e2e053bcea90be916ffa79f0555be65b852de62df9f53dd7c9e1e9e3218e4</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8b8dfb11f9032ae0b6693419a1d2172e93a9f8f76e33c01fca5a03358f344c4fab</Data>
  <Data size="48">38973a0ce8ae2d5bcf90805d6c1a8a3fa2ca38d91c78ee7affc5d6590eb605429989f20cbd9009ab66535640dd191b8e</Data>
  <Data size="64">4f605d1f09c0605a8a7ba69fd457681ced0fcf1d75a8f2c32b00dff73fe02395767a9cfce66672edb89b58e85adbda08a11f235d21ed0791e22d6598f103e716</Data>
  <Data size="48">f82c3052021a0a99b7d44461ff9adf8b72acf50b05133e3dc16973fbd92a9e41340ad1fc610070c7d2832f78a54bc3fc</Data>
  <Data size="64">30a0a8515875eac113192222962d6f90a481973e1fb92030443f7462b381b16cc7f0f89eb7541435b8751fe80b43044ebfc09918442136f7c835311d4db18f56</Data>
  <Data size="64">4f605d1f09c0605a8a7ba69fd457681ced0fcf1d75a8f2c32b00dff73fe0239526ab54a39e0cf7c9032d496aa720277938b04b89fe6ed0c89e13faf8b9ca95ac</Data>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="32">1d207f4be2288d830b9cee0073e06b1cd21c4840f352f8fcd946c2f8d5bd9f77</Data>
  <Data size="32">1d207f4be2288d830b9cee0073e06b1c351e1e880fc87a30d758bb8e135494af</Data>
  <Data size="48">1d207f4be2288d830b9cee0073e06b1c2ec63d68ca07e9ad0144e7140b40739d9ebd3c200ed5e8e18237260e55ba7c2b</Data>
  <Data size="32">1d207f4be2288d830b9cee0073e06b1c82eeafd9acbce6d7704c9973efe9b76c</Data>
  <Data size="112">1d207f4be2288d830b9cee0073e06b1c78a13b1d00c0c2aa82821c47c9cf5f23e6df3b212b6e01df96e9cf93e6c86b5f1480978f32fbcb605d7e3eadd4ad3a6afad74c42c17c5a5dd87232caa1742c030a7dc7f866cb99039bf52b8edc81186bc0eb7fb1806955caa6cb58a55bf74af5</Data>
</Block>
<Block>
  <Key privateKey="100021:98:23">87d3a12c27ae1f4f40635d1455c1587c9c0fcd0781c95e3a9698f969baabb72d3a1a212983f2718365a4ae350000000094a37177362a894e86e4d1ccff6d0ddc6ae30d5b3ae3d0bcede4b36d00000000</Key>
  <Data size="896">c2d2be4e86f277107f4946615448592f02f11b2fa2c482713db2aedaaa799f2d10bfc7182193e9620b7b8a45715f794d0cbca6f54f429381e28f9e102a0da42fd42fcf80caba529fa5a954465329e305cbe712c45065261f8531ae99727b903aa11e1338ec4fddd2b2d52e7d83091c64f961600ee10a0abc0cd8e69157eaeb3990ad29352d266d2c8850dd22ed8a538d4a6d78067d674dd20a046b10d294c4601e895255d59fe54f5608fd3b56f9a5854b4530bb8cbaae9f0f32e5f42eb4af67bf7fceabcf4624a1388de9ed6a1b9c144107491045ffc319bbe0bf77a12efb5322515c155188803b1c4670a62c9ad617fe348c5f4d600dd0421be943dc6191944de924e3cfe5811fe14ebbc8c07a48baea83ac343a73be627b4baf0581aedd98d4cd32c3fa4a7c603c9453e8592b1a1038a3ca8d7b3d2a3506902c1b6ba938fc43ab84daf9f98088b9324348adb4c41ba7f6717394c3a13c0176075530f2ea55681e2fda94c27b61648367382ab23d4cdbb3c233b61df7b1811860921868db92eef709a5a90421872fcf71331336702c06cd0a77c1aae0f4cf40b115078e27eec9bf12012426c179bcfbe93227ccc63f01a250152f0ae8e79e0daefd359772843e98a066fa917899fa799384318480667a6e7016e1460b73be65c996a58d18828877067799ba26cfa37a738c8a9ea564e77d81e52a9d974638c81ae587079e64f962479971ef453505f8098877b119d154d54b844b905ccaf98a36b0f85d689c55a411fe2f30d5badba08ef75304ed115e559c1b172e32f0ec24abce2ea82736a1fe1140f96bb82b90dce7363834b02422909e3c0d75b48f9ad5f7b1e87a986be447901cc629f5d2becb938281d85035598028cc0d6e5d083d43612ba942a7cf0a4efc566d8b65637e1e05d7c4c58ba0a6012448753c50bea4a77ec67178036c2514116da20d54aa105427751b3b8e517bcf86b230f6fcf307fbf29fd42e19c2a777613186108d00a1c07b4660eb4c0bac68b195fed8763b7f772e0b9ac2ec3b5aa2b6890b0ac35403fb438ab28921ea4b2691b55fe39cce7609c534736a296f4b3e128975047fccaf67b3ac219b2c227651f8a0e7b64acad86f3c38d72909f3708a90fc36843a4667759a50ff1de1b387ce55d014491bcf4d6aac413450be9d65a2b89733a9fddc867af437c1f3a9d03f5b5fdac29f01cfe9d219cfc85a953b310778fdbccbaf2634e056d301cf8c005fefccaed2e87e4b63e067e3b050756d</Data>
</Block>

**Comment by rudymentalewatson** [comment]
??

**Comment by leonv024** [comment]
Speak English. Also not the logs I asked for. I asked to run the payload with debug mode enabled and post the output.

**Comment by rudymentalewatson** [comment]
good morning
thanks for your answer
in the meantime I managed to get it to work they create a client and a server on virtual box but clearly only for studying and at my house (domestic LAN)
only doubt is that it is an executable and therefore if I use it in a machine that has an antivirus, it detects it immediately and I cannot go on
the next step would be to hide it in a pdf for example, or with a jpg, a word
do you have a demo package for this issue?
thank you

**Comment by unkownx753** [comment]
Hi check This error...
![Uploading Capture.PNG…]()
