### ISSUE TITLE
can't run RAASNET.py

### ISSUE THREAD

**Issue by rezafathikohi** [leonv024/RAASNet#61]
I did all the steps in kali linux but when I did run **python3 RAANET.py** the below error showed:

`# sudo python3 RAASNet.py       

Traceback (most recent call last):
  File "/home/kali/Desktop/RAASNet/RAASNet.py", line 1507, in <module>
    logon = Login()
  File "/home/kali/Desktop/RAASNet/RAASNet.py", line 151, in __init__
    Tk.__init__(self)
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2262, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
`

**Comment by leonv024** [comment]
It has a GUI and therefor needs a displat. You ran it without a displat/gui service.

**Comment by rezafathikohi** [comment]
What should i do then?

**Comment by leonv024** [comment]
Run it on a desktop environment like Windows, MacOS or Ubuntu.
