### ISSUE TITLE
I cant open the account to find decryption key

### ISSUE THREAD

**Issue by babajaga7765** [leonv024/RAASNet#63]
How to find the decryption key?

**Comment by leonv024** [comment]
IF the server was open and received the key, you can find it on the C&C. Link in readme. Login with your RAASNet account on the onion C&C.

Note: if your server did not receive the key, the key is lost and cannot be recovered.

You can test the server's connection with test_socket.py and view your test key on the C&C dashboard.

**Comment by babajaga7765** [comment]
Can you give me the link here. i tried some zenzo.nl and zenzo.org but i didnt find anything 
i tred the host of my ip and the default ip but i didnt find anything please give me some help
