### ISSUE TITLE
Offline Admin RAASNET

### ISSUE THREAD

**Issue by b4b857f6ee** [leonv024/RAASNet#64]
Hello,

I modify the RAASNET.py to use it offline like i found in one of the issue.
How can i have this interface? : https://github.com/leonv024/RAASNet/blob/master/demo/panel1.png

Thank you :)

**Comment by leonv024** [comment]
For that interface you'll need to navigate to the onion URL from the readme and login with your RAASNet account.
Note that if you use RAASNet offline, the onion panel won't contain any data because the client requires you to be logged in.

**Comment by b4b857f6ee** [comment]
Ok sad :(
