### ISSUE TITLE
Decryption key

### ISSUE THREAD

**Issue by babajaga7765** [leonv024/RAASNet#66]
#
![00643EE0-537A-4354-8335-242FB7DDA635](https://user-images.githubusercontent.com/79854320/110556709-5d1c7180-813f-11eb-9b60-1d8e1b62b419.jpeg)

are those the decryption key?

**Comment by leonv024** [comment]
Yes. You can verify the key by its 32-bit length.

**Comment by babajaga7765** [comment]
Ok thanks for everything you helped me a lot

**Comment by leonv024** [comment]
Glad I could help.
