### ISSUE TITLE
test socket.py

### ISSUE THREAD

**Issue by babajaga7767** [leonv024/RAASNet#67]
I try 
python3 test_socket.py 
Message sent: 10.0.2.13$Linux$71d2671f15e9357e9b9d864f596527d9$kali$kali

But i dont receive the message it stays the same
Server started on port [127.0.0.1] [8989]
Waiting...

When i saw ur video on youtube it was different
what should i do

**Comment by leonv024** [comment]
Just to clarify, did you ran the server and test_socket.py on the same machine?

**Comment by babajaga7765** [comment]
Yes

**Comment by leonv024** [comment]
no, I have no clue, it should work.

**Comment by babajaga7765** [comment]
Idk why its not working 

i think if test not work the payload will not work too and i will not get the decryption key

**Comment by leonv024** [comment]
that's correct.
