### ISSUE TITLE
Remote Server

### ISSUE THREAD

**Issue by alexonk** [leonv024/RAASNet#68]
Hi, I have successfully set up the tool.

Locally- everything works fine.

Remotely (Server & Victim on different machines)- Files get decrypted fine, but the server does not pick up that the payload has been executed. Meaning I do not receive the key for decryption.

Could you please assist me in this particular issue.

Thanks in advance.

**Comment by alexonk** [comment]
Thank you for the prompt response. 

I have set up the server on my local machine and I am running the payload on a virtual machine(bridged mode - windows server). 

![image](https://user-images.githubusercontent.com/47099606/110765918-9cf26e80-828f-11eb-9cf1-757afb0d8973.png)

Local machine IP
![image](https://user-images.githubusercontent.com/47099606/110765997-ada2e480-828f-11eb-8470-4f65b4521e55.png)

Victim machine IP (Windows server running on virtual machine bridged mode)
![image](https://user-images.githubusercontent.com/47099606/110766089-c8755900-828f-11eb-8adb-1dd5f8f44729.png)

I havent hosted it on the internet. What should I do?

**Comment by alexonk** [comment]
Hi I have solved this issue,

It was something to do with the firewall settings.

**Comment by leonv024** [comment]
Great. I'll close this issue.
