### ISSUE TITLE
Running Payload file in Ubuntu

### ISSUE THREAD

**Issue by aniketmahajan20** [leonv024/RAASNet#74]
Hi, how can I run the EXE payload file in ubuntu? When I double-click on it, it doesn't activate the ransomware.

**Comment by b4b857f6ee** [comment]
Hello,

You need to generate it on ubuntu.

**Comment by leonv024** [comment]
Hi,

You cannot run an EXE on Linux/Ubuntu. You'll have to move and compile the payload on Ubuntu.
