### ISSUE TITLE
ERROR line 48  geoip geolite2

### ISSUE THREAD

**Issue by 0000003** [leonv024/RAASNet#76]
i can´t open the raasnet.py this close automatically and says "no module named geo ip"

**Comment by leonv024** [comment]
Did you run pip3 install -r requirements.txt?

You're missing these modules:
python-geoip-python3
python-geoip-geolite2

**Comment by 0000003** [comment]
yes i run pip3 install -r requirements.txt

**Comment by 0000003** [comment]
now  no module named "requests"

**Comment by 0000003** [comment]
fixed thx

**Comment by asnlp** [comment]
Had a the same problem how did you resolve it?

**Comment by asnlp** [comment]
It also says this when I try to install Requirement already satisfied: python-geoip-python3
