### ISSUE TITLE
Error While Registering

### ISSUE THREAD

**Issue by aspiringpentester1** [leonv024/RAASNet#78]
![Screenshot_2021-05-24_21_35_20](https://user-images.githubusercontent.com/83753417/119426981-38647e80-bcd8-11eb-81ac-0501ae4f170a.png)

i tried registering and got a 404 error not sure why this happened
NOTE
I TRIED WITH REAL GMAIL ACCOUNTAND STILL FAILED

**Comment by leonv024** [comment]
No need to use a real Email. This makes no difference for the process. Registering a new user was broken, but I fixed it. Should be OK now.

**Comment by aspiringpentester1** [comment]
> No need to use a real Email. This makes no difference for the process. Registering a new user was broken, but I fixed it. Should be OK now.

so i should try the tool again deleting and downloading?

**Comment by leonv024** [comment]
no, the issue was server side. no need to update/redownload the client.
