### ISSUE TITLE
Is it not working on the virtual machine?

### ISSUE THREAD

**Issue by azo683001** [leonv024/RAASNet#8]
Fatal error detected
Failed to execute scripy payload

Is it not working on the virtual machine?

**Comment by leonv024** [comment]
It does. I've never had problems with it.
Can you execute the payload without any problems without compiling it?

**Comment by leonv024** [comment]
As you can see here, 
![Untitled](https://user-images.githubusercontent.com/33411715/76159216-5fa84d80-611e-11ea-84cc-24289a998825.png)
I just tested the current build and it works on Windows 10.

**Comment by azo683001** [comment]
Yes, I did not compile anything, I just created it.

**Comment by azo683001** [comment]
I recorded the question.
[https://youtu.be/EeXsIU9uPaw](url)

**Comment by leonv024** [comment]
Thank you. That's very helpful.
According to the video, pyinstaller is compiling with python 2.7 instead of 3.8.

![image](https://user-images.githubusercontent.com/33411715/76161580-08fa3e00-6135-11ea-8620-5bc99060e957.png)

**Comment by azo683001** [comment]
It's successful. 
I can continue to complete my school report, thank you very much. :)
![未命名](https://user-images.githubusercontent.com/61507260/76164698-e21b2680-618b-11ea-82f1-b4cc30ea9d1d.jpg)

**Comment by leonv024** [comment]
You're welcome.
