### ISSUE TITLE
Geoip problem

### ISSUE THREAD

**Issue by asnlp** [leonv024/RAASNet#83]
line 48, in <module>
    from geoip import geolite2
ModuleNotFoundError: No module named 'geoip'

I get this message whenever I run python3 RAASNet.py. I have both the geoip and geolite2 installed and when I run pip3 install -r requirements.txt Everything says that is has already been satisfied. 

Please help.

**Comment by leonv024** [comment]
Read the README. Try this: `sudo apt install python3-tk python3-pil python3-pil.imagetk libgeoip1 libgeoip-dev geoip-bin`
