### ISSUE TITLE
python3 RAASNet.py error

### ISSUE THREAD

**Issue by barrredemption7** [leonv024/RAASNet#87]
Traceback (most recent call last):
  File "RAASNet.py", line 1507, in <module>
    logon = Login()
  File "RAASNet.py", line 151, in __init__
    Tk.__init__(self)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by HugoMskn** [comment]
That's probably bcuz u are running it on a server and dont have a screen plugged in (I have the same issue)

**Comment by leonv024** [comment]
Correct.

**Comment by barrredemption7** [comment]
Please how can I install the screen plug ? Help me out

**Comment by barrredemption7** [comment]
Please how can I install the screen plug ? Help me out, I'm running the
raasnet on ubuntu
