### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Nicolasaandreas** [leonv024/RAASNet#9]
I get ERROR 500 error when I log in

I cannot log in. The program does not open.

can i run without login?

https://zeznzo.nl/login.py

**Comment by leonv024** [comment]
I'm aware. The login service has been down all morning.
I'm at the office atm and unable to fix the error.

My apologies.

**Comment by Nicolasaandreas** [comment]
thank you.

what can we do to run offline in such cases

can it work without a connection to the server?

**Comment by leonv024** [comment]
Yes, sure.
Open the RAASNet.py file.
All the way at the bottom of the RAASNet.py file, where it says:

```Python
logon = Login()
logon.mainloop()
```

Replace it with:
```Python
#logon = Login()
#logon.mainloop()
main = MainWindow('Foo', 'fakepwd', 'foo@bar.nl', 'foo', 'bar', 'User', 'Active')
main.mainloop()
```

**Comment by leonv024** [comment]
Server is fixed. Login works.
You can use the RAASNet portal and tool again.
