### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by Investoh47** [leonv024/RAASNet#93]
I tried using pia VPN with the provided port forwarding, host: 127.0.0.1 but was not able to get the system details including the decryption key, how do I fix this?

**Comment by leonv024** [comment]
For RAASNet to work with PIA you'll need the victim on a remote network. It doesn't work if the server and victim are in the same LAN.

**Comment by Investoh47** [comment]
Thanks I understand properly

**Comment by Investoh47** [comment]
I hope i can use my local IP right?

**Comment by leonv024** [comment]
you can use the local IP of your VPN adapter as server host.

**Comment by Investoh47** [comment]
Thanks, what if my local IP change?, My local IP was 10.32.0.10 when I
generated the payload but my local IP change to 10.32.0.6 now, Will I still
get the key ?

**Comment by leonv024** [comment]
If the IP changes, the server will no longer receive the keys.

**Comment by Investoh47** [comment]
Ok, thanks. Which name and profile does if it show if message is sent to
WildixEnum users?

**Comment by leonv024** [comment]
The given name. You can set a random name without an Email address and connect, it should be ok.
